name: "Traffic Map Generator"
description: "Génère une carte de trafic avec overlay Azure"
version: "1.0.0"
slug: "traffic_map"
url: "https://github.com/lexou/hassio-addons"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
map:
  - config:rw
  - share:rw
options:
  latitude: 43.604500
  longitude: 1.444200
  zoom: 15
  width: 1000
  height: 640
  update_interval: 300
  azure_key: ""
schema:
  latitude: float
  longitude: float
  zoom: int(1,20)
  width: int(100,2000)
  height: int(100,2000)
  update_interval: int(60,3600)
  azure_key: password
